apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rubicure-playground
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'

    spec:
      containerConcurrency: 10
      timeoutSeconds: 5
      serviceAccountName: rubicure-app@rubicure-playground.iam.gserviceaccount.com
      containers:
        - image: asia-northeast1-docker.pkg.dev/rubicure-playground/rubicure-playground/app:sha-__GITHUB_SHA__
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: 128Mi

          env:
            # - name: PUMA_PORT
            #   value: "8080"
            # - name: PUMA_WORKERS
            #   value: "1"
            # - name: PUMA_MIN_THREADS
            #   value: "1"
            - name: PUMA_MAX_THREADS
              value: "10"

  traffic:
    - percent: 100
      latestRevision: true
